// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYGi2SEzkR1sr1g7LCe-1P3iIdvmathfo',
    appId: '1:829972798062:web:060f29130d6cf62cf9247f',
    messagingSenderId: '829972798062',
    projectId: 'landledger-africa',
    authDomain: 'landledger-africa.firebaseapp.com',
    storageBucket: 'landledger-africa.firebasestorage.app',
    measurementId: 'G-VGZCY9ZF1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYAhTzZQ7era3DtCnKDxCTZm_tkEIw_sg',
    appId: '1:829972798062:android:883ad2fdfff29562f9247f',
    messagingSenderId: '829972798062',
    projectId: 'landledger-africa',
    storageBucket: 'landledger-africa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQhtXgTkYGfFcPvBIzffbCr-qgI5DO23M',
    appId: '1:829972798062:ios:7a44ccae06bbe703f9247f',
    messagingSenderId: '829972798062',
    projectId: 'landledger-africa',
    storageBucket: 'landledger-africa.firebasestorage.app',
    iosClientId: '829972798062-j97p91tqtc5nlvqu1pv9hrnvd2nae7vh.apps.googleusercontent.com',
    iosBundleId: 'com.example.landledgerFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQhtXgTkYGfFcPvBIzffbCr-qgI5DO23M',
    appId: '1:829972798062:ios:7a44ccae06bbe703f9247f',
    messagingSenderId: '829972798062',
    projectId: 'landledger-africa',
    storageBucket: 'landledger-africa.firebasestorage.app',
    iosClientId: '829972798062-j97p91tqtc5nlvqu1pv9hrnvd2nae7vh.apps.googleusercontent.com',
    iosBundleId: 'com.example.landledgerFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYGi2SEzkR1sr1g7LCe-1P3iIdvmathfo',
    appId: '1:829972798062:web:000bd520695ad717f9247f',
    messagingSenderId: '829972798062',
    projectId: 'landledger-africa',
    authDomain: 'landledger-africa.firebaseapp.com',
    storageBucket: 'landledger-africa.firebasestorage.app',
    measurementId: 'G-EETXEP6TBF',
  );

}